# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'awsl' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for awsl
  pod 'NotificationBannerSwift'
  pod 'Charts'
  
#  source 'https://github.com/CocoaPods/Specs.git'
  pod 'Localize-Swift', '~> 2.0'

end
